// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: protofiles/email.proto

package protofiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailValidationService_SendEmailValidation_FullMethodName = "/protofiles.EmailValidationService/SendEmailValidation"
)

// EmailValidationServiceClient is the client API for EmailValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailValidationServiceClient interface {
	SendEmailValidation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type emailValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailValidationServiceClient(cc grpc.ClientConnInterface) EmailValidationServiceClient {
	return &emailValidationServiceClient{cc}
}

func (c *emailValidationServiceClient) SendEmailValidation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, EmailValidationService_SendEmailValidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailValidationServiceServer is the server API for EmailValidationService service.
// All implementations must embed UnimplementedEmailValidationServiceServer
// for forward compatibility.
type EmailValidationServiceServer interface {
	SendEmailValidation(context.Context, *EmailRequest) (*EmailResponse, error)
	mustEmbedUnimplementedEmailValidationServiceServer()
}

// UnimplementedEmailValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailValidationServiceServer struct{}

func (UnimplementedEmailValidationServiceServer) SendEmailValidation(context.Context, *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailValidation not implemented")
}
func (UnimplementedEmailValidationServiceServer) mustEmbedUnimplementedEmailValidationServiceServer() {
}
func (UnimplementedEmailValidationServiceServer) testEmbeddedByValue() {}

// UnsafeEmailValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailValidationServiceServer will
// result in compilation errors.
type UnsafeEmailValidationServiceServer interface {
	mustEmbedUnimplementedEmailValidationServiceServer()
}

func RegisterEmailValidationServiceServer(s grpc.ServiceRegistrar, srv EmailValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailValidationService_ServiceDesc, srv)
}

func _EmailValidationService_SendEmailValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailValidationServiceServer).SendEmailValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailValidationService_SendEmailValidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailValidationServiceServer).SendEmailValidation(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailValidationService_ServiceDesc is the grpc.ServiceDesc for EmailValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.EmailValidationService",
	HandlerType: (*EmailValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailValidation",
			Handler:    _EmailValidationService_SendEmailValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/email.proto",
}
